printf "a string, no processing:<%s>\n" "A\nB"
printf "a string, no processing:<%b>\n" "A\nB"
printf "www.runoob.com\a\n"
printf "\a"
printf "%d %s %c\n" 1 "abc" "def"
printf "%s %d %c\n" "abc" 1 "def"
printf "%b\n" "\777"
printf "\777"
